[project]
name = "ansible2nix"
version = "0.1.0"
description = "convert requirements.yml into a nix expression"
authors = [{name="Matthieu Coudron", email = "mcoudron@hotmail.com"}]
license = "GPL"
dependencies = [
  "PyYAML (>=6.0,<7.0)",
]
requires-python = ">=3.10"


[tool.poetry.scripts]
ansible2nix = 'ansible2nix.ansible2nix:main'


[build-system]
requires = [
	"poetry-core>=2.0.0",
	"setuptools>50"  # use my own
]
build-backend = "poetry.core.masonry.api"
